[build]
  functions = "netlify/functions"

[functions]
  # Bundle Netlify Functions with esbuild and allow external deps
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/blobs"]

# Hourly schedule for sports-refresh (top of every hour, UTC)
[[scheduled.functions]]
  name = "sports-refresh"
  cron = "0 * * * *"

# Redirect scoreboard requests to Netlify Functions
[[redirects]]
  from = "/sports/celtics"
  to   = "/.netlify/functions/celtics"
  status = 200

[[redirects]]
  from = "/stocks/sna"
  to   = "/.netlify/functions/sna"
  status = 200

# HTML: always revalidate
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Functions: conservative caching (Netlify still returns no-store; fine)
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Cache-Control = "no-cache"

# Static assets: long-lived and immutable (you cache-bust with ?v=<hash>)
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
