[build]
  functions = "netlify/functions"

# Configure Netlify Functions
[functions]
  # Bundle with esbuild for modern syntax support (required for ESM and schedule helper)
  node_bundler = "esbuild"
  # Ensure external modules are installed for Netlify Functions
  external_node_modules = ["@netlify/blobs"]

# Schedule the sports-refresh function to run hourly instead of daily. The cron
# expression "0 * * * *" triggers at the top of every hour in UTC.
[functions."sports-refresh"]
  schedule = "0 * * * *"


# Security headers[
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Content-Security-Policy = "default-src 'self'; img-src 'self' data:; script-src 'self' plausible.io; style-src 'self' fonts.googleapis.com cdn.jsdelivr.net; font-src 'self' fonts.gstatic.com cdn.jsdelivr.net; connect-src 'self'; frame-ancestors 'none';"
