const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
const src=fs.readFileSync('public/scripts/cluster-swarm-live-v8.js','utf8');
const context={localStorage:{getItem:()=>null}};vm.createContext(context);
vm.runInContext(src.slice(src.indexOf('  let auditBatch ='),src.indexOf("  const WORKSPACE_KEY=")),context);
assert.deepEqual(Array.from(context.browserWorkers({browser_workers:['Alina','Alina','Nexus']})),['Alina','Nexus']);
assert.throws(()=>context.browserWorkers({browser_workers:['RenderRig']}),/browser_workers/);
assert.throws(()=>context.browserCommand('/; touch /tmp/test'),/Invalid/);
assert(context.browserCommand('/shop/').includes("--path '/shop/'"));
assert(context.browserCommand(null,true).includes('python3'));
const page={url:'https://curtbrag.com/',viewports:[{viewport:'mobile',findings:[{check:'horizontal-overflow',evidence:'10px',proposal:'Constrain the element.'}]}]};
const reports=context.auditReports([{job_id:'browser-audit-v1-1',device_id:'Alina',exit_code:0,stdout:JSON.stringify({kind:'website-browser-audit',page})},{job_id:'audit-v1-1',device_id:'phone173',exit_code:0,stdout:JSON.stringify({kind:'website-audit',page:{url:'https://curtbrag.com/',issues:[]}})}]);
assert.equal(reports.length,2);assert.equal(reports[0].mode,'Chromium');assert.equal(reports[0].proposals[0].proposal,'Constrain the element.');
assert.equal(context.auditReports([{job_id:'browser-audit-v1-2',exit_code:1,stdout:JSON.stringify({kind:'website-browser-audit',page})}])[0].url,'Incomplete check');
vm.runInContext("auditBatch='audit-v1-current';browserAuditBatch='browser-audit-v1-current'",context);
assert.equal(context.auditReports([{job_id:'audit-v1-old'},{job_id:'browser-audit-v1-old'}]).length,0);
console.log('Browser audit commands, worker selection, incomplete results and combined findings validated');
const restored={localStorage:{getItem:()=>JSON.stringify({http_batch:'audit-v1-saved',browser_batch:'browser-audit-v1-saved'}),setItem:()=>{}}};vm.createContext(restored);
vm.runInContext(src.slice(src.indexOf('  let auditBatch ='),src.indexOf("  const WORKSPACE_KEY=")),restored);
assert.equal(restored.auditReports([{job_id:'audit-v1-old'}]).length,0);
assert.equal(restored.auditReports([{job_id:'browser-audit-v1-saved-0',exit_code:0,stdout:JSON.stringify({kind:'website-browser-audit',page})}]).length,1);
console.log('Latest batch filtering survives browser storage restoration');

const plan=context.auditFixPlan(reports,{settings:{paths:['/'],browser_workers:['Alina']}});
assert.equal(plan.status,'review-required');assert.equal(plan.tasks.length,1);
assert.equal(plan.tasks[0].evidence,'10px');assert(plan.tasks[0].validation.includes('mobile'));
const clean=context.auditFixPlan([{url:'https://curtbrag.com/',mode:'Chromium',issues:[],viewports:[{viewport:'mobile',pending_images:2,blocked_resource_hosts:['example.com']}]}],{settings:{paths:['/']}});
assert.equal(clean.status,'no-detected-fixes');assert.equal(clean.tasks.length,0);assert(clean.coverage_gaps.some(g=>g.includes('2 images')));
assert.equal(context.auditFixPlan([],{settings:{paths:['/']}}).status,'incomplete');
assert.equal(context.auditFixPlan([{url:'Incomplete check',worker:'Alina',issues:['failed']}],{settings:{paths:['/']}}).status,'incomplete');
console.log('Evidence, validation, clean checks and incomplete coverage validated');

const delivery={tasks:[{job_id:'a',worker:'Alina',status:'queued'},{job_id:'b',worker:'Nexus',status:'submitting'},{job_id:'c',worker:'Alina',status:'unsent'},{job_id:'d',worker:'Nexus',status:'unsent'}]};
assert.deepEqual(Array.from(context.auditUnsent(delivery,{jobs:[{id:'b'}],results:[{job_id:'c',device_id:'Alina'}]}),t=>t.job_id),['d']);
assert.equal(context.auditUnsent(null,{jobs:[],results:[]}).length,0);
console.log('Submission recovery skips acknowledged, queued and completed assignments');
// Evidence must outlive the server's bounded result history and remain isolated by batch.
let evidenceSaved;
const evidenceContext={localStorage:{getItem:()=>evidenceSaved||null,setItem:(k,v)=>{evidenceSaved=v;}}};
vm.createContext(evidenceContext);
const auditSource=src.slice(src.indexOf('  let auditBatch ='),src.indexOf('  const WORKSPACE_KEY='));
vm.runInContext(auditSource,evidenceContext);
vm.runInContext("auditBatch='audit-v1-saved';auditRecord={http_batch:auditBatch,tasks:[]}",evidenceContext);
const result={job_id:'audit-v1-saved-0',device_id:'phone173',exit_code:0,stdout:JSON.stringify({kind:'website-audit',page:{url:'https://curtbrag.com/',issues:[]}})};
assert.equal(evidenceContext.auditReports([result,result]).length,1);
assert.equal(evidenceContext.auditReports([]).length,1);
const evidenceReload={localStorage:evidenceContext.localStorage};vm.createContext(evidenceReload);vm.runInContext(auditSource,evidenceReload);
assert.equal(evidenceReload.auditReports([])[0].url,'https://curtbrag.com/');
assert.equal(evidenceReload.auditReports([{...result,job_id:'audit-v1-saved-other-0'}]).length,1);
const failed={...result,exit_code:1,stdout:'',stderr:'failed'};
assert.equal(evidenceReload.auditReports([result,failed])[0].url,'https://curtbrag.com/');
vm.runInContext("auditBatch='audit-v1-new';auditRecord={http_batch:auditBatch,tasks:[]}",evidenceReload);
assert.equal(evidenceReload.auditReports([]).length,0);
console.log('Audit evidence survives expiration and reload, deduplicates results, and stays within its batch');
(async()=>{
 let saved, calls=[], fail=true;
 const server={jobs:[],results:[],nodes:[{id:'Alina',online:true}]};
 const ctx={localStorage:{getItem:()=>saved||null,setItem:(k,v)=>{saved=v;}},load:async()=>{},swarmApi:async(action,method,body)=>{
  if(action==='queue-status')return server;
  calls.push(body.job.id);
  if(body.job.id==='two'&&fail)throw new Error('connection interrupted');
  server.jobs.push({id:body.job.id});return {};
 }};
 vm.createContext(ctx);vm.runInContext(src.slice(src.indexOf('  let auditBatch ='),src.indexOf('  const WORKSPACE_KEY=')),ctx);
 vm.runInContext(`auditRecord={tasks:[{job_id:'one',worker:'Alina',cmd:'safe',status:'unsent'},{job_id:'two',worker:'Alina',cmd:'safe',status:'unsent'}]}`,ctx);
 await assert.rejects(ctx.submitAuditTasks(),/interrupted/);
 assert.equal(JSON.parse(saved).tasks[0].status,'queued');assert.equal(JSON.parse(saved).tasks[1].status,'unconfirmed');
 fail=false;calls=[];
 const afterReload={...ctx};vm.createContext(afterReload);vm.runInContext(src.slice(src.indexOf('  let auditBatch ='),src.indexOf('  const WORKSPACE_KEY=')),afterReload);
 await afterReload.submitAuditTasks();assert.deepEqual(calls,['two']);
 console.log('Interrupted submission survives reload and retries only the remaining assignment');
})().catch(error=>{console.error(error);process.exitCode=1;});
