const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
const src=fs.readFileSync('public/scripts/cluster-swarm-live-v8.js','utf8');
const code=src.slice(src.indexOf('  function researchEpisodeSpec('),src.indexOf('  function renderPublishingPackage('));
const context={};vm.createContext(context);vm.runInContext(code,context);
vm.runInContext(src.slice(src.indexOf('  function reviewedDraftRecord('),src.indexOf('  function openDraftReview(')),context);
const record={status:'succeeded',job_id:'draft-1',sources:[{id:'S1',title:'Electric vehicle',url:'https://en.wikipedia.org/wiki/Electric_vehicle'},{id:'S2',title:'Unused',url:'https://en.wikipedia.org/wiki/Unused'}],output:{draft:{title:'Electric Vehicle Research',points:[{text:'A battery stores energy.',sources:['S1']}],verification:'Check full source.'}}};
const pack=context.researchPublishingPackage(record);
assert.equal(pack.sources.length,1);assert.equal(pack.source_job_id,'draft-1');assert.equal(pack.review_required,true);
assert(pack.platforms.youtube.description.includes(record.output.draft.points[0].text));
assert(pack.platforms.instagram.caption.includes(record.sources[0].url));
assert(!pack.platforms.instagram.caption.includes(record.sources[1].url));
assert.equal(Object.keys(pack.platforms).join(','),'youtube,tiktok,instagram,facebook');
record.sources[0].url='javascript:alert(1)';assert.throws(()=>context.researchPublishingPackage(record),/valid Wikipedia/);
record.sources[0].url='https://en.wikipedia.org/wiki/Electric_vehicle';record.output.draft.points[0].sources=['S99'];assert.throws(()=>context.researchPublishingPackage(record),/unknown source/);
console.log('Publishing package preserves narration, scopes credits, supports four platforms and rejects invalid references');
record.output.draft.points[0].sources=['S1'];
const before=JSON.stringify(record),review={title:'Reviewed battery explanation',points:[{text:'A reviewed claim.',sources:['S1']}],verification:'Check the complete article.'};
const edited=context.reviewedDraftRecord(record,review);
assert.equal(JSON.stringify(record),before,'review must not mutate the original');
review.points[0].text='Changed after validation';
assert.equal(edited.output.draft.points[0].text,'A reviewed claim.');
assert(context.researchPublishingPackage(edited).platforms.instagram.caption.includes('A reviewed claim.'));
assert(context.researchEpisodeSpec(edited).scenes.some(s=>s.narration==='A reviewed claim.'));
assert.throws(()=>context.reviewedDraftRecord(record,{...review,points:[{text:'Bad reference',sources:['S99']}]}),/unknown source/);
assert.throws(()=>context.reviewedDraftRecord(record,{...review,verification:'bad\nnotes'}),/Verification/);
assert.throws(()=>context.reviewedDraftRecord(record,{...review,title:'x'.repeat(76)}),/75 characters/);
assert.throws(()=>context.reviewedDraftRecord({...record,status:'queued'},review),/Complete/);
console.log('Reviewed drafts retain source validation, preserve originals and feed both captions and video settings');
