name: Export Actions Runs (1–56)

on:
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build runs report
        id: build
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const owner = 'curtbrag';
            const repo = 'curtbrag-website';

            // 1) Get up to 100 workflow runs
            const runs = await github.request('GET /repos/{owner}/{repo}/actions/runs', {
              owner, repo, per_page: 100
            });

            // 2) Keep runs 1..56 and sort ascending by run number
            const wanted = runs.data.workflow_runs
              .filter(r => r.run_number <= 56)
              .sort((a,b) => a.run_number - b.run_number);

            // 3) Compose Markdown table with filenames and statuses
            const lines = [
              '| Run | Date (UTC) | Status | SHA | Message | Files (name + status) |',
              '|---:|---|---|---|---|---|'
            ];

            for (const r of wanted) {
              const sha = r.head_sha;
              // commit details (includes per-file changes)
              const commit = await github.request('GET /repos/{owner}/{repo}/commits/{sha}', {
                owner, repo, sha
              });

              const files = (commit.data.files || [])
                .map(f => `${f.filename} (${f.status})`)
                .join('<br>');

              const msg = (r.head_commit?.message || '').replace(/\n/g, ' ');
              lines.push(`| ${r.run_number} | ${r.created_at} | ${r.conclusion || r.status} | ${sha.slice(0,7)} | ${msg} | ${files} |`);
            }

            fs.writeFileSync('runs-1-56.md', lines.join('\n'));

      - name: Commit report (this push will trigger Pages = Run #58)
        run: |
          git config user.name "actions-bot"
          git config user.email "actions@users.noreply.github.com"
          git add runs-1-56.md
          git commit -m "Add runs 1–56 report (and trigger Pages deploy #58)"
          git push
