name: Update Sports Live

on:
  schedule:
    - cron: '0 3 * * *' # 03:00 UTC = 11pm Eastern
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install node-fetch@3
      - name: Run live sports update script
        run: node scripts/update-sports-live.js
      - name: Commit changes
        run: |
          git config user.name "sports-bot"
          git config user.email "sports-bot@users.noreply.github.com"
          git add assets/sports.json
          git commit -m "Live sports update" || echo "No changes to commit"
      - name: Push changes
        run: git push
